---
title: "Working-doc"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(tidyterra)
library(sf)
library(terra)
#library(maps)
#library(ggmap)
#library(osmdata)



##36.83957, -76.25027

#initial raster creation and organization
unclean.norf <- rast("Data/VA_Southern_GCS_3m_NAVDm.tif")
bbox <- ext(c(xmin = -76.389548, xmax = -76.256, ymin = 36.87, ymax = 36.971082))
unclean.norf.masked <- mask(unclean.norf, bbox)
unclean.norf.trimmed <- trim(unclean.norf.masked)
plot(unclean.norf.trimmed)
writeRaster(unclean.norf.trimmed, "Data/unclean-norf-trimmed.tif", overwrite = TRUE)
ggplot()+
  geom_spatraster(data = unclean.norf.trimmed)
ggsave(filename = "norfolk-initial.png", path = "Plots/")
#decided to save intermediates just to track progress



#creating a one with less resolution for usein the app
  raster.small5 <- terra::aggregate(unclean.norf.trimmed, fact = 5)
  plot(raster.small)
  writeRaster(raster.small5, "Data/raster-small5.tif", overwrite = TRUE)
  
  
#this is to filter for certain elevations. needs to be re ran each change.
unclean.norf.trimmed.filtered <- unclean.norf.trimmed
unclean.norf.trimmed.filtered[unclean.norf.trimmed.filtered >= 1] <- NA #change this
#for different elevations, not sure what unit it is yet
plot(unclean.norf.trimmed.filtered)
ggplot()+
  geom_spatraster(data = unclean.norf.trimmed.filtered)
ggsave(filename = "norfolk-filtered.png", path = "Plots/")


#im thinking we can use this functino from terra called sieve() to filter the unconnected low-lying areas and make them a different color or also more likely the function terra::patches() !!!!!

#then we can overlay that one as a mask onto the first one to get just the NOT hydrologically connected parts,  and then we can put the two together with different colors.

norf.patches.test <- patches(unclean.norf.trimmed.filtered, 
                             directions = 8, 
                             values = FALSE, 
                             zeroAsNA=FALSE)
#this takes hellllaaaa long btw



plot(norf.patches.test)
ggplot()+
  geom_spatraster(data = norf.patches.test)+
  scale_fill_gradientn(colors = c("darkblue", "green", "yellow"))
ggsave(filename = "norfolk-patches.png", path = "Plots/")
#ok so we can wsee it plotted each patch assigning a different number, now need to find the lowest number or the largest patch

freq(norf.patches.test)
#from this we can see the layer 1, value one, have the most. So this is the 
#hydrologically connected. Now need to isolate just this layer/value of 1

# soooooo maybe set all the other layers to na
# can probably also use max()

biggest.patch.elev.1 <- norf.patches.test
biggest.patch.elev.1[biggest.patch.elev.1 != 1] <- NA


#soo this one shows all the connected areas that will flood for elevaction of 1
#still need to find units for this BTW but I think its meters
plot(biggest.patch.elev.1)


#now to mask to get the unconnected areas

other.patches.elev.1 <- mask(norf.patches.test, biggest.patch.elev.1, inverse=TRUE)
plot(other.patches.elev.1)

# now setting this one to have the same value of like 50 for plotting PURPOSES

other.patches.elev.1.uniform <- other.patches.elev.1
other.patches.elev.1.uniform[!is.na(other.patches.elev.1.uniform)] <- 50
plot(other.patches.elev.1.uniform)



combined.elev.1 <- merge(other.patches.elev.1.uniform, biggest.patch.elev.1)
plot(combined.elev.1)
ggplot()+
  geom_spatraster(data = combined.elev.1)+
  scale_fill_gradient(low = "skyblue", high = "yellow")
ggsave(filename = "norfolk-elev-1.png", path = "Plots/")

###also I think for the shiny app, we could use sieve() and patches() to create .tifs for each increment of elevation, in like a big DF to plot easier idk


## now im tryna get the basemap to put under spatraster data
# crs(combined.elev.1)
# 
# 
# counties.map <- maps::map("county", plot = FALSE, fill = TRUE)
# 
# 
# counties.map <- st_as_sf(counties.map, crs = 4269)
# 
# ggplot()+
#   geom_spatraster(data = combined.elev.1)+
#   scale_fill_gradient(low = "skyblue", high = "yellow")+
#   geom_sf(data = counties.map, fill = NA)+
#   coord_sf(
#     xlim = c(-76.389548, -76.154689),
#     ylim = c(36.834249, 36.971082))

#not very persice lowk so maybe ill give up on that. Should porbably get a good basemap from somewhere else


#now trying pacakge ggmap

# norfolk.basemap <- get_map(location = "norfolk, virginia", maptype = "roadmap")
#                              
# 
# 
# counties.map <- st_as_sf(counties.map, crs = 4269)
# 
# ggplot()+
#   geom_spatraster(data = combined.elev.1)+
#   scale_fill_gradient(low = "skyblue", high = "yellow")+
#   geom_sf(data = counties.map, fill = NA)+
#   coord_sf(
#     xlim = c(-76.389548, -76.154689),
#     ylim = c(36.834249, 36.971082))
#apparently you need api key for ts

# now will try OSM maps/????
```


```{r}
#Trying to figrue out merging a raster shp file with street data with DEM file
library(terra)
library(sf)
install.packages("tigris")
library(tigris)
#created a road map of noroflk
norfolk_roads <- roads(state = "VA", county = "Norfolk")

# Saving shapefile
st_write(norfolk_roads, "norfolk_roads.shp", delete_dsn = TRUE)

plot(norfolk_roads$geometry)
norfolk_roads$FULLNAME


ggplot()+
   geom_spatraster(data = combined.elev.1)+
        scale_fill_gradient(low = "skyblue", high = "yellow")+
        theme(
          plot.background  = element_rect(fill = "white", color = NA),
          panel.background = element_rect(fill = "white", color = NA)
        )+
  geom_sf(data = norfolk_roads, mapping = aes())

```


```{r}
# data set link to coverage — https://wu-next-prod.wunderground.com/article/forecast/regional/news/2025-10-08-noreaster-coastal-storm-forecast-wind-flooding-october#:~:text=In%20Virginia%2C%20coastal%20flooding%20was,of%20our%20parent%20company%2C%20IBM.
# 2025 Oct 09 - 2025 Oct 13
sample.set <- "Data/Tide_Sensors_20251128.csv"
```

